<!-- ignoring style turning_circle-casing -->
<!-- ignoring style turning_circle-fill -->
<!-- ignoring style landuse_overlay -->
<!-- ignoring style area-text -->
<!-- ignoring style highway-junctions -->
<!-- ignoring style text -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #ffffff -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #fdfdfd -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #ececec -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #cacaca -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #afafaf -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #a1a1a1 -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #9b9b9b -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: #999999 -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: white -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: #999999 -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: white -->
<!-- ignoring minor-roads-fill_highway_is_platform_or_railway_is_platform: grey -->
<!-- ignoring minor-roads-fill_highway_is_platform_or_railway_is_platform: #bbbbbb -->
<!-- ignoring other minor-roads-fill_highway_is_steps: #fff -->
<!-- ignoring other minor-roads-fill_highway_is_steps: salmon -->
<!-- ignoring style access -->
<!-- ignoring other guideways_railway_is_tram_and_bridge_is_yes: white -->
<!-- ignoring other guideways_railway_is_tram_and_bridge_is_yes: #6666ff -->
<!-- ignoring other guideways_railway_is_tram_and_bridge_is_yes: white -->
<!-- ignoring style roads-text-ref-low-zoom -->
<!-- ignoring style roads-text-ref -->
<!-- ignoring style roads-text-name -->
<!-- ignoring style cliffs -->
<!-- ignoring style barriers_area -->
<!-- ignoring style barriers -->
<!-- ignoring style directions -->
<!-- ignoring style boundary -->
<!-- ignoring style theme_park -->
<!-- ignoring style hillshade-vhd -->
<!-- ignoring style slope-vhd -->
<!-- ignoring style relief-vhd -->
<!-- ignoring style necountries -->
<!-- ignoring style nepopulated -->
<!-- ignoring style landcover -->
<!-- ignoring style landcover_line -->
<!-- ignoring style sports_grounds -->
<!-- ignoring style contour10 -->
<!-- ignoring style contour100-labels -->
<!-- ignoring style contour100 -->
<!-- ignoring style contour500-labels -->
<!-- ignoring style contour500 -->
<!-- ignoring style contour1000-labels -->
<!-- ignoring style contour1000 -->
<!-- ignoring style water_areas -->
<!-- ignoring style water-areas-overlay -->
<!-- ignoring style glaciers-text -->
<!-- ignoring style water-lines-casing -->
<!-- ignoring style water-lines-low-zoom -->
<!-- ignoring style water_lines -->
<!-- ignoring style dam -->
<!-- ignoring style marinas-area -->
<!-- ignoring style piers-area -->
<!-- ignoring style piers -->
<!-- ignoring style locks -->
<!-- ignoring style citywalls -->
<!-- ignoring style castle_walls -->
<!-- ignoring style buildings-lz -->
<!-- ignoring style buildings -->
<!-- ignoring style ferry-routes -->
<!-- ignoring style aerialways -->
<!-- ignoring style continent -->
<!-- ignoring style country -->
<!-- ignoring style state -->
<!-- ignoring style capital -->
<!-- ignoring style city -->
<!-- ignoring style town -->
<!-- ignoring style suburb -->
<!-- ignoring style village -->
<!-- ignoring style hamlet -->
<!-- ignoring style stations -->
<!-- ignoring style symbols -->
<!-- ignoring style points -->
<!-- ignoring style housenumbers -->
<!-- ignoring style housenames -->

<!-- #000 -->
<!ENTITY tunnels-casing_highway_is_motorway_or_highway_is_motorway_link "#000">
<!ENTITY tunnels-casing_highway_is_trunk_or_highway_is_trunk_link "#000">
<!ENTITY tunnels-casing_highway_is_primary_or_highway_is_primary_link "#000">
<!ENTITY tunnels-casing_highway_is_secondary_or_highway_is_secondary_link "#000">
<!ENTITY minor-roads-casing-links_highway_is_motorway_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing-links_highway_is_trunk_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing-links_highway_is_primary_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing-links_highway_is_secondary_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_motorway_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_trunk_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_primary_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_secondary_and_not_tunnel_is_yes "#000">
<!ENTITY waterway-bridges_tracktype_is_grade5 "#000">
<!ENTITY waterway-bridges_tracktype_is_grade5 "#000">
<!ENTITY bridges_casing_highway_is_motorway_or_highway_is_motorway_link "#000">
<!ENTITY bridges_casing_highway_is_trunk_or_highway_is_trunk_link "#000">
<!ENTITY bridges_casing_highway_is_primary_or_highway_is_primary_link "#000">

<!-- #3086bf -->
<!ENTITY minor-roads-fill-links_highway_is_motorway_link_and_not_tunnel_is_yes "#3086bf">
<!ENTITY minor-roads-fill_highway_is_motorway_and_not_tunnel_is_yes "#3086bf">
<!ENTITY bridges_fill_highway_is_motorway_or_highway_is_motorway_link "#3086bf">
<!ENTITY roads_highway_is_motorway_or_highway_is_motorway_link "#3086bf">

<!-- #3f7f3f -->
<!ENTITY minor-roads-fill-links_highway_is_secondary_link_and_not_tunnel_is_yes "#3f7f3f">
<!ENTITY minor-roads-fill_highway_is_secondary_and_not_tunnel_is_yes "#3f7f3f">
<!ENTITY bridges_fill_highway_is_secondary_or_highway_is_secondary_link "#3f7f3f">
<!ENTITY roads_highway_is_secondary_or_highway_is_secondary_link "#3f7f3f">

<!-- #444 -->
<!ENTITY minor-roads-fill_railway_is_tram_and_tunnel_is_yes "#444">
<!ENTITY trams_railway_is_tram "#444">
<!ENTITY trams_railway_is_tram_and_not_bridge_is_yes "#444">
<!ENTITY trams_railway_is_tram_and_bridge_is_yes "#444">

<!-- #555 -->
<!ENTITY bridges_casing_railway_is_light_rail_or_railway_is_narrow_gauge "#555">

<!-- #666 -->
<!ENTITY minor-roads-fill_q_railway_is_narrow_gauge_or_railway_is_funicular_p_and_not_tunnel_is_yes "#666">
<!ENTITY minor-roads-fill_q_railway_is_narrow_gauge_or_railway_is_funicular_p_and_tunnel_is_yes "#666">
<!ENTITY minor-roads-fill_railway_is_light_rail_and_tunnel_is_yes "#666">
<!ENTITY minor-roads-fill_railway_is_light_rail_and_not_tunnel_is_yes "#666">
<!ENTITY bridges_fill_railway_is_light_rail_or_railway_is_narrow_gauge "#666">

<!-- #6666ff -->
<!ENTITY guideways_railway_is_tram_and_bridge_is_yes "#6666ff">

<!-- #777 -->
<!ENTITY roads_railway_is_monorail "#777">

<!-- #82b6d9 -->
<!ENTITY tunnels-fill_highway_is_motorway_or_highway_is_motorway_link "#82b6d9">

<!-- #82d982 -->
<!ENTITY tunnels-fill_highway_is_secondary_or_highway_is_secondary_link "#82d982">

<!-- #996600 -->
<!ENTITY highway-area-casing_highway_is_track "#996600">
<!ENTITY minor-roads-fill_highway_is_track "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade3 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade4 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade3 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade4 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade5 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_not_tracktype_isnot_empty "#996600">

<!-- #999 -->
<!ENTITY highway-area-casing_highway_is_residential_or_highway_is_unclassified "#999">
<!ENTITY tunnels-casing_highway_is_tertiary_or_highway_is_tertiary_link "#999">
<!ENTITY tunnels-casing_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#999">
<!ENTITY tunnels-casing_highway_is_tertiary_or_highway_is_tertiary_link_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#999">
<!ENTITY minor-roads-casing_q_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes "#999">
<!ENTITY minor-roads-casing_highway_is_service_and_not_q_service_is_INT_minus_minor_or_tunnel_is_yes_p "#999">
<!ENTITY minor-roads-casing_highway_is_service_and_tunnel_is_yes "#999">
<!ENTITY minor-roads-casing_highway_is_service_and_service_is_INT_minus_minor "#999">
<!ENTITY minor-roads-fill_railway_is_miniature "#999">
<!ENTITY minor-roads-fill_railway_is_subway_and_tunnel_is_yes "#999">
<!ENTITY minor-roads-fill_railway_is_subway_and_not_tunnel_is_yes "#999">
<!ENTITY minor-roads-fill_railway_is_turntable "#999">
<!ENTITY bridges_fill_railway_is_subway "#999">

<!-- #999999 -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_not_tunnel_is_yes "#999999">
<!ENTITY bridges_fill_railway_is_rail "#999999">
<!ENTITY bridges_fill_railway_is_rail "#999999">
<!ENTITY bridges_fill_railway_is_INT_minus_spur_minus_siding_minus_yard "#999999">
<!ENTITY roads_railway_is_preserved "#999999">
<!ENTITY roads_railway_is_INT_minus_preserved_minus_ssy "#999999">

<!-- #9b9b9b -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#9b9b9b">

<!-- #a1a1a1 -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#a1a1a1">

<!-- #a87000 -->
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade2 "#a87000">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "#a87000">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade2 "#a87000">

<!-- #aaa -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard "#aaa">
<!ENTITY minor-roads-fill_q_railway_is_narrow_gauge_or_railway_is_funicular_p_and_tunnel_is_yes "#aaa">
<!ENTITY roads_railway_is_rail "#aaa">
<!ENTITY roads_railway_is_rail_and_not_tunnel_is_yes "#aaa">
<!ENTITY roads_railway_is_rail_and_tunnel_is_yes "#aaa">
<!ENTITY roads_railway_is_tram_or_railway_is_light_rail_or_railway_is_narrow_gauge_or_railway_is_funicular "#aaa">
<!ENTITY roads_railway_is_preserved "#aaa">
<!ENTITY roads_railway_is_INT_minus_preserved_minus_ssy "#aaa">

<!-- #afafaf -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#afafaf">

<!-- #b37700 -->
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade1 "#b37700">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "#b37700">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade1 "#b37700">

<!-- #b5d0d0 -->
<!ENTITY waterway-bridges_tracktype_is_grade5 "#b5d0d0">
<!ENTITY waterway-bridges_tracktype_is_grade5 "#b5d0d0">

<!-- #bbb -->
<!ENTITY minor-roads-casing-links_highway_is_tertiary_link_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_highway_is_tertiary_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_q_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_q_highway_is_tertiary_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-fill_highway_is_tertiary_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#bbb">

<!-- #bbbbbb -->
<!ENTITY minor-roads-fill_highway_is_service_and_not_service_is_INT_minus_minor "#bbbbbb">

<!-- #bbc -->
<!ENTITY minor-roads-fill_aeroway_is_runway "#bbc">
<!ENTITY minor-roads-fill_aeroway_is_runway_and_not_bridge_is_yes "#bbc">
<!ENTITY minor-roads-fill_aeroway_is_taxiway "#bbc">
<!ENTITY minor-roads-fill_aeroway_is_taxiway_and_not_bridge_is_yes "#bbc">
<!ENTITY bridges_fill_aeroway_is_runway "#bbc">
<!ENTITY bridges_fill_aeroway_is_taxiway "#bbc">

<!-- #bf3030 -->
<!ENTITY minor-roads-fill-links_highway_is_primary_link_and_not_tunnel_is_yes "#bf3030">
<!ENTITY minor-roads-fill_highway_is_primary_and_not_tunnel_is_yes "#bf3030">
<!ENTITY bridges_fill_highway_is_primary_or_highway_is_primary_link "#bf3030">
<!ENTITY roads_highway_is_primary_or_highway_is_primary_link "#bf3030">

<!-- #bf30bf -->
<!ENTITY minor-roads-fill-links_highway_is_trunk_link_and_not_tunnel_is_yes "#bf30bf">
<!ENTITY minor-roads-fill_highway_is_trunk_and_not_tunnel_is_yes "#bf30bf">
<!ENTITY bridges_fill_highway_is_trunk_or_highway_is_trunk_link "#bf30bf">
<!ENTITY roads_highway_is_trunk_or_highway_is_trunk_link "#bf30bf">
<!ENTITY roads_highway_is_trunk_or_highway_is_trunk_link "#bf30bf">

<!-- #cacaca -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#cacaca">

<!-- #ccc -->
<!ENTITY minor-roads-fill_highway_is_living_street "#ccc">
<!ENTITY roads_railway_is_tram_or_railway_is_light_rail_or_railway_is_narrow_gauge_or_railway_is_funicular "#ccc">

<!-- #d98282 -->
<!ENTITY tunnels-fill_highway_is_primary_or_highway_is_primary_link "#d98282">

<!-- #d982d9 -->
<!ENTITY tunnels-fill_highway_is_trunk_or_highway_is_trunk_link "#d982d9">

<!-- #ddd -->
<!ENTITY minor-roads-fill_highway_is_road "#ddd">
<!ENTITY bridges_fill_highway_is_road "#ddd">

<!-- #debd9c -->
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#debd9c">
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#debd9c">
<!ENTITY bridges_fill_highway_is_unsurfaced "#debd9c">

<!-- #ececec -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#ececec">

<!-- #ededed -->
<!ENTITY minor-roads-fill_highway_is_pedestrian "#ededed">
<!ENTITY bridges_fill_highway_is_pedestrian "#ededed">

<!-- #fdfdfd -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#fdfdfd">

<!-- #ffc -->
<!ENTITY tunnels-fill_highway_is_tertiary_or_highway_is_tertiary_link "#ffc">

<!-- #ffcc00 -->
<!ENTITY bridges_fill_highway_is_byway "#ffcc00">

<!-- #fff -->
<!ENTITY tunnels-fill_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#fff">
<!ENTITY minor-roads-fill_q_railway_is_narrow_gauge_or_railway_is_funicular_p_and_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_q_highway_is_residential_or_highway_is_unclassified_p_and_not_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_highway_is_service_and_service_is_INT_minus_minor "#fff">
<!ENTITY minor-roads-fill_q_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_p_and_not_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_q_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_p_and_not_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#fff">
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#fff">
<!ENTITY footbikecycle-tunnels_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p "#fff">
<!ENTITY footbikecycle-tunnels_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p "#fff">
<!ENTITY roads_railway_is_monorail "#fff">

<!-- #ffffb3 -->
<!ENTITY minor-roads-fill-links_highway_is_tertiary_link_and_not_tunnel_is_yes "#ffffb3">
<!ENTITY minor-roads-fill_highway_is_tertiary_and_not_tunnel_is_yes "#ffffb3">
<!ENTITY bridges_fill_highway_is_tertiary_or_highway_is_tertiary_link "#ffffb3">

<!-- #ffffff -->
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes "#ffffff">

<!-- black -->
<!ENTITY minor-roads-fill_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_and_not_tunnel_is_yes "black">
<!ENTITY footbikecycle-tunnels_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p "black">
<!ENTITY bridges_casing_highway_is_motorway_or_highway_is_motorway_link "black">
<!ENTITY bridges_casing_highway_is_trunk_or_highway_is_trunk_link "black">
<!ENTITY bridges_casing_highway_is_primary_or_highway_is_primary_link "black">
<!ENTITY bridges_casing_highway_is_secondary_or_highway_is_secondary_link "black">
<!ENTITY bridges_casing_highway_is_tertiary_or_highway_is_tertiary_link "black">
<!ENTITY bridges_casing_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "black">
<!ENTITY bridges_casing_highway_is_service "black">
<!ENTITY bridges_casing_highway_is_pedestrian "black">
<!ENTITY bridges_casing_aeroway_is_runway "black">
<!ENTITY bridges_casing_aeroway_is_taxiway "black">
<!ENTITY bridges_casing_railway_is_subway "black">
<!ENTITY bridges_casing_highway_is_unsurfaced "black">
<!ENTITY bridges_casing_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p "black">
<!ENTITY bridges_casing_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p "black">
<!ENTITY bridges_casing_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p "black">
<!ENTITY bridges_casing_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p "black">
<!ENTITY bridges_casing_highway_is_byway "black">
<!ENTITY bridges_casing_railway_is_rail "black">
<!ENTITY bridges_casing_railway_is_INT_minus_spur_minus_siding_minus_yard "black">
<!ENTITY bridges_casing_q_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_p_and_not_highway_isnot_empty "black">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade1 "black">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade2 "black">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade3 "black">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade4 "black">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade5 "black">
<!ENTITY bridges_casing_highway_is_track_and_not_tracktype_isnot_empty "black">
<!ENTITY bridges_fill_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p "black">
<!ENTITY trams_railway_is_tram_and_bridge_is_yes "black">

<!-- blue -->
<!ENTITY minor-roads-fill_q_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_p_and_not_tunnel_is_yes "blue">
<!ENTITY footbikecycle-tunnels_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p "blue">
<!ENTITY bridges_fill_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p "blue">

<!-- green -->
<!ENTITY minor-roads-fill_q_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_p_and_not_tunnel_is_yes "green">
<!ENTITY footbikecycle-tunnels_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p "green">
<!ENTITY bridges_fill_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p "green">

<!-- grey -->
<!ENTITY highway-area-casing_highway_is_pedestrian_or_highway_is_service_or_highway_is_footway_or_highway_is_path "grey">
<!ENTITY highway-area-casing_highway_is_platform_or_railway_is_platform "grey">
<!ENTITY minor-roads-casing_highway_is_pedestrian_and_not_tunnel_is_yes "grey">
<!ENTITY minor-roads-casing_highway_is_pedestrian_and_tunnel_is_yes "grey">
<!ENTITY footbikecycle-tunnels_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p "grey">
<!ENTITY footbikecycle-tunnels_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p "grey">
<!ENTITY footbikecycle-tunnels_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p "grey">
<!ENTITY footbikecycle-tunnels_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "grey">
<!ENTITY bridges_fill_q_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_p_and_not_highway_isnot_empty "grey">

<!-- pink -->
<!ENTITY minor-roads-casing-links_highway_is_raceway "pink">

<!-- salmon -->
<!ENTITY minor-roads-fill_highway_is_steps "salmon">
<!ENTITY minor-roads-fill_q_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_p_and_not_tunnel_is_yes "salmon">
<!ENTITY footbikecycle-tunnels_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p "salmon">
<!ENTITY bridges_fill_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p "salmon">

<!-- white -->
<!ENTITY minor-roads-casing_highway_is_living_street "white">
<!ENTITY minor-roads-fill_railway_is_spur_minus_siding_minus_yard_and_not_tunnel_is_yes "white">
<!ENTITY minor-roads-fill_highway_is_service_and_not_service_is_INT_minus_minor "white">
<!ENTITY minor-roads-fill_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_and_not_tunnel_is_yes "white">
<!ENTITY minor-roads-fill_q_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_p_and_not_tunnel_is_yes "white">
<!ENTITY minor-roads-fill_highway_is_track "white">
<!ENTITY footbikecycle-tunnels_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p "white">
<!ENTITY footbikecycle-tunnels_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p "white">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade1 "white">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade2 "white">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade3 "white">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade4 "white">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "white">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "white">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "white">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "white">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "white">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "white">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "white">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "white">
<!ENTITY bridges_casing2_railway_is_subway "white">
<!ENTITY bridges_casing2_railway_is_light_rail_or_railway_is_narrow_gauge "white">
<!ENTITY bridges_casing2_highway_is_unsurfaced "white">
<!ENTITY bridges_casing2_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p "white">
<!ENTITY bridges_casing2_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p "white">
<!ENTITY bridges_casing2_highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p "white">
<!ENTITY bridges_casing2_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p "white">
<!ENTITY bridges_casing2_highway_is_byway "white">
<!ENTITY bridges_casing2_railway_is_rail "white">
<!ENTITY bridges_casing2_railway_is_INT_minus_spur_minus_siding_minus_yard "white">
<!ENTITY bridges_casing2_q_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_p_and_not_highway_isnot_empty "white">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade1 "white">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade2 "white">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade3 "white">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade4 "white">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade5 "white">
<!ENTITY bridges_casing2_highway_is_track_and_not_tracktype_isnot_empty "white">
<!ENTITY bridges_fill_highway_is_residential_or_highway_is_unclassified "white">
<!ENTITY bridges_fill_highway_is_service "white">
<!ENTITY bridges_fill_railway_is_rail "white">
<!ENTITY bridges_fill_railway_is_rail "white">
<!ENTITY bridges_fill_railway_is_INT_minus_spur_minus_siding_minus_yard "white">
<!ENTITY roads_railway_is_preserved "white">
<!ENTITY roads_railway_is_INT_minus_preserved_minus_ssy "white">
<!ENTITY trams_railway_is_tram_and_bridge_is_yes "white">

<!ENTITY aeroway_is_runway_11-11_minor-roads-fill "2">
<!ENTITY aeroway_is_runway_12-12_minor-roads-fill "4">
<!ENTITY aeroway_is_runway_13-13_minor-roads-fill "7">
<!ENTITY aeroway_is_runway_14-18_bridges_casing "19">
<!ENTITY aeroway_is_runway_14-18_bridges_fill "18">
<!ENTITY aeroway_is_runway_and_not_bridge_is_yes_14-18_minor-roads-fill "18">
<!ENTITY aeroway_is_taxiway_11-13_minor-roads-fill "1">
<!ENTITY aeroway_is_taxiway_14-14_bridges_casing "5">
<!ENTITY aeroway_is_taxiway_14-14_bridges_fill "4">
<!ENTITY aeroway_is_taxiway_15-18_bridges_casing "7">
<!ENTITY aeroway_is_taxiway_15-18_bridges_fill "6">
<!ENTITY aeroway_is_taxiway_and_not_bridge_is_yes_14-14_minor-roads-fill "4">
<!ENTITY aeroway_is_taxiway_and_not_bridge_is_yes_15-18_minor-roads-fill "6">
<!ENTITY highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_13-18_footbikecycle-tunnels "2">
<!ENTITY highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_14-18_bridges_casing "5.5">
<!ENTITY highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_14-18_bridges_casing2 "4">
<!ENTITY highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_14-18_bridges_fill "1.5">
<!ENTITY highway_is_byway_14-18_bridges_casing "5.5">
<!ENTITY highway_is_byway_14-18_bridges_casing2 "4">
<!ENTITY highway_is_byway_14-18_bridges_fill "1.5">
<!ENTITY highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_13-18_footbikecycle-tunnels "2">
<!ENTITY highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_14-18_bridges_casing "5.5">
<!ENTITY highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_14-18_bridges_casing2 "4">
<!ENTITY highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_14-18_bridges_fill "1.5">
<!ENTITY highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_13-18_footbikecycle-tunnels "2.5">
<!ENTITY highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_14-18_bridges_casing "6">
<!ENTITY highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_14-18_bridges_casing2 "4.5">
<!ENTITY highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_14-18_bridges_fill "2.0">
<!ENTITY highway_is_living_street_12-13_minor-roads-casing "2.5">
<!ENTITY highway_is_living_street_12-13_minor-roads-fill "1.5">
<!ENTITY highway_is_living_street_14-14_minor-roads-casing "4">
<!ENTITY highway_is_living_street_14-14_minor-roads-fill "3">
<!ENTITY highway_is_living_street_15-15_minor-roads-casing "6">
<!ENTITY highway_is_living_street_15-15_minor-roads-fill "4.7">
<!ENTITY highway_is_living_street_16-16_minor-roads-casing "9">
<!ENTITY highway_is_living_street_16-16_minor-roads-fill "7.4">
<!ENTITY highway_is_living_street_17-18_minor-roads-casing "14.5">
<!ENTITY highway_is_living_street_17-18_minor-roads-fill "13">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_12-12_minor-roads-casing "3">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_12-12_minor-roads-fill "2">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_13-14_minor-roads-casing "6.5">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_13-14_minor-roads-fill "5">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_15-16_minor-roads-casing "10">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_15-16_minor-roads-fill "8.5">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_17-18_minor-roads-casing "13">
<!ENTITY highway_is_motorway_and_not_tunnel_is_yes_17-18_minor-roads-fill "11">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_12-12_minor-roads-casing-links "1.5">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_12-12_minor-roads-fill-links "0.5">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_13-14_minor-roads-casing-links "4.5">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_13-14_minor-roads-fill-links "3">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_15-16_minor-roads-casing-links "8">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_15-16_minor-roads-fill-links "6.5">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_17-18_minor-roads-casing-links "11">
<!ENTITY highway_is_motorway_link_and_not_tunnel_is_yes_17-18_minor-roads-fill-links "9">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_10-10_roads "2">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_11-11_roads "2.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_12-12_bridges_casing "3">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_12-12_bridges_fill "2">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_12-12_tunnels-casing "3">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_12-12_tunnels-fill "2">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_13-14_bridges_casing "6.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_13-14_bridges_fill "5.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_13-14_tunnels-casing "6.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_13-14_tunnels-fill "5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_15-16_bridges_casing "9">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_15-16_bridges_fill "7.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_15-16_tunnels-casing "10">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_15-16_tunnels-fill "8.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_17-18_bridges_casing "12">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_17-18_bridges_fill "10">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_17-18_tunnels-casing "13">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_17-18_tunnels-fill "11">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_5-6_roads "0.5">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_7-8_roads "1">
<!ENTITY highway_is_motorway_or_highway_is_motorway_link_9-9_roads "1.4">
<!ENTITY highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_13-18_footbikecycle-tunnels "0.5">
<!ENTITY highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_14-18_bridges_casing "4">
<!ENTITY highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_14-18_bridges_casing2 "2.5">
<!ENTITY highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_14-18_bridges_fill "0.5">
<!ENTITY highway_is_path_and_not_q_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_p_and_not_tunnel_is_yes_13-18_minor-roads-fill "0.5">
<!ENTITY highway_is_pedestrian_13-13_bridges_casing "2.2">
<!ENTITY highway_is_pedestrian_13-13_bridges_fill "1.5">
<!ENTITY highway_is_pedestrian_13-13_minor-roads-fill "1.5">
<!ENTITY highway_is_pedestrian_14-14_bridges_casing "3.8">
<!ENTITY highway_is_pedestrian_14-14_bridges_fill "3">
<!ENTITY highway_is_pedestrian_14-14_minor-roads-fill "3">
<!ENTITY highway_is_pedestrian_15-15_bridges_casing "7">
<!ENTITY highway_is_pedestrian_15-15_bridges_fill "5.5">
<!ENTITY highway_is_pedestrian_15-15_minor-roads-fill "5.5">
<!ENTITY highway_is_pedestrian_16-18_bridges_casing "9.5">
<!ENTITY highway_is_pedestrian_16-18_bridges_fill "8">
<!ENTITY highway_is_pedestrian_16-18_minor-roads-fill "8">
<!ENTITY highway_is_pedestrian_and_not_tunnel_is_yes_13-13_minor-roads-casing "2">
<!ENTITY highway_is_pedestrian_and_not_tunnel_is_yes_14-14_minor-roads-casing "3.6">
<!ENTITY highway_is_pedestrian_and_not_tunnel_is_yes_15-15_minor-roads-casing "6.5">
<!ENTITY highway_is_pedestrian_and_not_tunnel_is_yes_16-18_minor-roads-casing "9">
<!ENTITY highway_is_pedestrian_and_tunnel_is_yes_13-13_minor-roads-casing "2">
<!ENTITY highway_is_pedestrian_and_tunnel_is_yes_14-14_minor-roads-casing "3.6">
<!ENTITY highway_is_pedestrian_and_tunnel_is_yes_15-15_minor-roads-casing "6.5">
<!ENTITY highway_is_pedestrian_and_tunnel_is_yes_16-18_minor-roads-casing "9">
<!ENTITY highway_is_pedestrian_or_highway_is_service_or_highway_is_footway_or_highway_is_path_14-18_highway-area-casing "1">
<!ENTITY highway_is_platform_or_railway_is_platform_16-18_highway-area-casing "2">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_11-12_minor-roads-fill "2.5">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_12-12_minor-roads-casing "3">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_13-14_minor-roads-casing "7.5">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_13-14_minor-roads-fill "7">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_15-16_minor-roads-casing "11.5">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_15-16_minor-roads-fill "11">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_17-18_minor-roads-casing "16">
<!ENTITY highway_is_primary_and_not_tunnel_is_yes_17-18_minor-roads-fill "15.5">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_12-12_minor-roads-casing-links "3">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_12-12_minor-roads-fill-links "2.5">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_13-14_minor-roads-casing-links "7.5">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_13-14_minor-roads-fill-links "7">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_15-16_minor-roads-casing-links "11.5">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_15-16_minor-roads-fill-links "11">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_17-18_minor-roads-casing-links "16">
<!ENTITY highway_is_primary_link_and_not_tunnel_is_yes_17-18_minor-roads-fill-links "15.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_10-10_roads "2">
<!ENTITY highway_is_primary_or_highway_is_primary_link_11-11_roads "2.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_12-12_bridges_casing "4">
<!ENTITY highway_is_primary_or_highway_is_primary_link_12-12_bridges_fill "3">
<!ENTITY highway_is_primary_or_highway_is_primary_link_12-12_tunnels-casing "4">
<!ENTITY highway_is_primary_or_highway_is_primary_link_12-12_tunnels-fill "2.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_13-14_bridges_casing "8">
<!ENTITY highway_is_primary_or_highway_is_primary_link_13-14_bridges_fill "7">
<!ENTITY highway_is_primary_or_highway_is_primary_link_13-14_tunnels-casing "8">
<!ENTITY highway_is_primary_or_highway_is_primary_link_13-14_tunnels-fill "6.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_15-16_bridges_casing "11">
<!ENTITY highway_is_primary_or_highway_is_primary_link_15-16_bridges_fill "9.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_15-16_tunnels-casing "11">
<!ENTITY highway_is_primary_or_highway_is_primary_link_15-16_tunnels-fill "9">
<!ENTITY highway_is_primary_or_highway_is_primary_link_17-18_bridges_casing "16">
<!ENTITY highway_is_primary_or_highway_is_primary_link_17-18_bridges_fill "14.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_17-18_tunnels-casing "14">
<!ENTITY highway_is_primary_or_highway_is_primary_link_17-18_tunnels-fill "12">
<!ENTITY highway_is_primary_or_highway_is_primary_link_7-8_roads "0.5">
<!ENTITY highway_is_primary_or_highway_is_primary_link_9-9_roads "1.2">
<!ENTITY highway_is_raceway_12-12_minor-roads-casing-links "1.2">
<!ENTITY highway_is_raceway_13-14_minor-roads-casing-links "4">
<!ENTITY highway_is_raceway_15-18_minor-roads-casing-links "7">
<!ENTITY highway_is_residential_or_highway_is_unclassified_14-14_bridges_fill "3.5">
<!ENTITY highway_is_residential_or_highway_is_unclassified_14-18_highway-area-casing "1">
<!ENTITY highway_is_residential_or_highway_is_unclassified_15-15_bridges_fill "7.5">
<!ENTITY highway_is_residential_or_highway_is_unclassified_16-16_bridges_fill "9.5">
<!ENTITY highway_is_residential_or_highway_is_unclassified_17-18_bridges_fill "14">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_13-13_tunnels-casing "3">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_13-13_tunnels-fill "2">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_14-14_bridges_casing "4.5">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_14-14_tunnels-casing "4.5">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_14-14_tunnels-fill "3">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_15-15_bridges_casing "9">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_15-15_tunnels-casing "8">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_15-15_tunnels-fill "6.5">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_16-16_bridges_casing "11">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_16-16_tunnels-casing "11">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_16-16_tunnels-fill "9.4">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_17-18_bridges_casing "16">
<!ENTITY highway_is_residential_or_highway_is_unclassified_or_highway_is_road_17-18_tunnels-fill "13">
<!ENTITY highway_is_road_13-13_minor-roads-fill "2">
<!ENTITY highway_is_road_14-14_bridges_fill "3.5">
<!ENTITY highway_is_road_14-14_minor-roads-fill "3">
<!ENTITY highway_is_road_15-15_minor-roads-fill "6.5">
<!ENTITY highway_is_road_15-16_bridges_fill "9.5">
<!ENTITY highway_is_road_16-16_minor-roads-fill "9.4">
<!ENTITY highway_is_road_17-18_bridges_fill "14">
<!ENTITY highway_is_road_17-18_minor-roads-fill "13">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_12-12_minor-roads-casing "2.5">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_12-12_minor-roads-fill "2">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_13-14_minor-roads-casing "8.5">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_13-14_minor-roads-fill "8">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_15-16_minor-roads-casing "11.5">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_15-16_minor-roads-fill "11">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_17-18_minor-roads-casing "16">
<!ENTITY highway_is_secondary_and_not_tunnel_is_yes_17-18_minor-roads-fill "15.5">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_12-12_minor-roads-casing-links "2.5">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_12-12_minor-roads-fill-links "2">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_13-14_minor-roads-casing-links "8.5">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_13-14_minor-roads-fill-links "8">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_15-16_minor-roads-casing-links "11.5">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_15-16_minor-roads-fill-links "11">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_17-18_minor-roads-casing-links "16">
<!ENTITY highway_is_secondary_link_and_not_tunnel_is_yes_17-18_minor-roads-fill-links "15.5">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_11-11_roads "2">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_12-12_tunnels-casing "4">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_12-12_tunnels-fill "2">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_13-14_bridges_casing "10">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_13-14_bridges_fill "9">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_13-14_tunnels-casing "10">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_13-14_tunnels-fill "8">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_15-16_bridges_casing "12">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_15-16_bridges_fill "10.5">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_15-16_tunnels-casing "12">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_15-16_tunnels-fill "10">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_17-18_bridges_casing "16">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_17-18_bridges_fill "14.5">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_17-18_tunnels-casing "17">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_17-18_tunnels-fill "14">
<!ENTITY highway_is_secondary_or_highway_is_secondary_link_9-10_roads "1">
<!ENTITY highway_is_service_14-15_bridges_casing "3">
<!ENTITY highway_is_service_14-15_bridges_fill "2">
<!ENTITY highway_is_service_16-18_bridges_casing "8">
<!ENTITY highway_is_service_16-18_bridges_fill "6">
<!ENTITY highway_is_service_and_not_q_service_is_INT_minus_minor_or_tunnel_is_yes_p_14-15_minor-roads-casing "2.5">
<!ENTITY highway_is_service_and_not_q_service_is_INT_minus_minor_or_tunnel_is_yes_p_16-18_minor-roads-casing "7">
<!ENTITY highway_is_service_and_not_service_is_INT_minus_minor_13-13_minor-roads-fill "1">
<!ENTITY highway_is_service_and_not_service_is_INT_minus_minor_14-15_minor-roads-fill "2">
<!ENTITY highway_is_service_and_not_service_is_INT_minus_minor_16-18_minor-roads-fill "6">
<!ENTITY highway_is_service_and_service_is_INT_minus_minor_16-18_minor-roads-casing "4">
<!ENTITY highway_is_service_and_service_is_INT_minus_minor_16-18_minor-roads-fill "3">
<!ENTITY highway_is_service_and_tunnel_is_yes_14-15_minor-roads-casing "2.5">
<!ENTITY highway_is_service_and_tunnel_is_yes_16-18_minor-roads-casing "7">
<!ENTITY highway_is_steps_13-14_minor-roads-fill "2.0">
<!ENTITY highway_is_steps_15-18_minor-roads-fill "5.0">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_13-13_minor-roads-casing "6">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_13-13_minor-roads-fill "4.5">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_14-14_minor-roads-casing "7.5">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_14-14_minor-roads-fill "6">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_15-16_minor-roads-casing "11">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_15-16_minor-roads-fill "9.4">
<!ENTITY highway_is_tertiary_and_not_tunnel_is_yes_17-18_minor-roads-fill "13">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_13-13_minor-roads-casing-links "6">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_13-13_minor-roads-fill-links "4.5">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_14-14_minor-roads-casing-links "7.5">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_14-14_minor-roads-fill-links "6">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_15-16_minor-roads-casing-links "11">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_15-16_minor-roads-fill-links "9.4">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_17-18_minor-roads-casing-links "16">
<!ENTITY highway_is_tertiary_link_and_not_tunnel_is_yes_17-18_minor-roads-fill-links "13">
<!ENTITY highway_is_tertiary_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_10-12_minor-roads-fill "1">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_13-13_tunnels-casing "6">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_13-13_tunnels-fill "5">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_14-14_bridges_casing "7.5">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_14-14_bridges_fill "6">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_14-14_tunnels-casing "7.5">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_14-14_tunnels-fill "6.5">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_15-16_bridges_casing "11">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_15-16_bridges_fill "9.5">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_15-16_tunnels-casing "11">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_15-16_tunnels-fill "9.4">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_17-18_bridges_casing "16">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_17-18_bridges_fill "14">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_17-18_tunnels-fill "13">
<!ENTITY highway_is_tertiary_or_highway_is_tertiary_link_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_17-18_tunnels-casing "16">
<!ENTITY highway_is_track_13-13_minor-roads-fill "1.2">
<!ENTITY highway_is_track_14-18_highway-area-casing "2">
<!ENTITY highway_is_track_and_not_tracktype_isnot_empty_14-18_bridges_casing "4.5">
<!ENTITY highway_is_track_and_not_tracktype_isnot_empty_14-18_bridges_casing2 "3">
<!ENTITY highway_is_track_and_not_tracktype_isnot_empty_14-18_bridges_fill "1.5">
<!ENTITY highway_is_track_and_tracktype_is_grade1_14-18_bridges_casing "5">
<!ENTITY highway_is_track_and_tracktype_is_grade1_14-18_bridges_casing2 "3.5">
<!ENTITY highway_is_track_and_tracktype_is_grade1_14-18_bridges_fill "2">
<!ENTITY highway_is_track_and_tracktype_is_grade2_14-18_bridges_casing "4.5">
<!ENTITY highway_is_track_and_tracktype_is_grade2_14-18_bridges_casing2 "3">
<!ENTITY highway_is_track_and_tracktype_is_grade2_14-18_bridges_fill "1.5">
<!ENTITY highway_is_track_and_tracktype_is_grade3_14-18_bridges_casing "4.5">
<!ENTITY highway_is_track_and_tracktype_is_grade3_14-18_bridges_casing2 "3.5">
<!ENTITY highway_is_track_and_tracktype_is_grade3_14-18_bridges_fill "2">
<!ENTITY highway_is_track_and_tracktype_is_grade4_14-18_bridges_casing "4.5">
<!ENTITY highway_is_track_and_tracktype_is_grade4_14-18_bridges_casing2 "3">
<!ENTITY highway_is_track_and_tracktype_is_grade4_14-18_bridges_fill "2">
<!ENTITY highway_is_track_and_tracktype_is_grade5_14-18_bridges_casing "4.5">
<!ENTITY highway_is_track_and_tracktype_is_grade5_14-18_bridges_casing2 "3">
<!ENTITY highway_is_track_and_tracktype_is_grade5_14-18_bridges_fill "2">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_12-12_minor-roads-casing "3">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_12-12_minor-roads-fill "2.5">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_13-14_minor-roads-casing "7.5">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_13-14_minor-roads-fill "7">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_15-16_minor-roads-casing "11.5">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_15-16_minor-roads-fill "11">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_17-18_minor-roads-casing "16">
<!ENTITY highway_is_trunk_and_not_tunnel_is_yes_17-18_minor-roads-fill "15.5">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_12-12_minor-roads-casing-links "3">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_12-12_minor-roads-fill-links "2.5">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_13-14_minor-roads-casing-links "7.5">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_13-14_minor-roads-fill-links "7">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_15-16_minor-roads-casing-links "11.5">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_15-16_minor-roads-fill-links "11">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_17-18_minor-roads-casing-links "16">
<!ENTITY highway_is_trunk_link_and_not_tunnel_is_yes_17-18_minor-roads-fill-links "15.5">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_11-11_roads "2.5">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_12-12_bridges_casing "4">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_12-12_bridges_fill "3">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_12-12_tunnels-casing "4">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_12-12_tunnels-fill "2.5">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_13-14_bridges_casing "8">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_13-14_bridges_fill "7">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_13-14_tunnels-casing "8">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_13-14_tunnels-fill "6.5">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_15-16_bridges_casing "11">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_15-16_bridges_fill "9.5">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_15-16_tunnels-casing "11">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_15-16_tunnels-fill "9">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_17-18_bridges_casing "16">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_17-18_bridges_fill "14.5">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_17-18_tunnels-casing "14">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_17-18_tunnels-fill "12">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_5-6_roads "0.4">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_7-8_roads "1">
<!ENTITY highway_is_trunk_or_highway_is_trunk_link_9-10_roads "2">
<!ENTITY highway_is_unsurfaced_13-13_bridges_casing "5">
<!ENTITY highway_is_unsurfaced_13-13_bridges_casing2 "4">
<!ENTITY highway_is_unsurfaced_13-13_bridges_fill "3">
<!ENTITY highway_is_unsurfaced_13-13_minor-roads-fill "2.5">
<!ENTITY highway_is_unsurfaced_14-18_bridges_casing "6.5">
<!ENTITY highway_is_unsurfaced_14-18_bridges_casing2 "5">
<!ENTITY highway_is_unsurfaced_14-18_bridges_fill "4">
<!ENTITY highway_is_unsurfaced_14-18_minor-roads-fill "4">
<!ENTITY q_highway_is_bridleway_or_q_highway_is_path_and_horse_is_designated_p_p_and_not_tunnel_is_yes_13-18_minor-roads-fill "1.2">
<!ENTITY q_highway_is_cycleway_or_q_highway_is_path_and_bicycle_is_designated_p_p_and_not_tunnel_is_yes_13-18_minor-roads-fill "1.2">
<!ENTITY q_highway_is_footway_or_q_highway_is_path_and_foot_is_designated_p_p_and_not_tunnel_is_yes_13-18_minor-roads-fill "1.5">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes_13-13_minor-roads-casing "3">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes_14-14_minor-roads-casing "4.5">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes_15-15_minor-roads-casing "8">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes_16-16_minor-roads-casing "11">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_p_and_not_tunnel_is_yes_13-13_minor-roads-fill "2">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_p_and_not_tunnel_is_yes_14-14_minor-roads-fill "3">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_p_and_not_tunnel_is_yes_15-15_minor-roads-fill "6.5">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_p_and_not_tunnel_is_yes_16-16_minor-roads-fill "9.4">
<!ENTITY q_highway_is_residential_or_highway_is_unclassified_p_and_not_tunnel_is_yes_17-18_minor-roads-fill "13">
<!ENTITY q_highway_is_tertiary_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_p_and_not_tunnel_is_yes_17-18_minor-roads-casing "16">
<!ENTITY q_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_p_and_not_highway_isnot_empty_13-18_bridges_casing "6">
<!ENTITY q_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_p_and_not_highway_isnot_empty_13-18_bridges_casing2 "4.5">
<!ENTITY q_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_p_and_not_highway_isnot_empty_13-18_bridges_fill "2">
<!ENTITY q_railway_is_narrow_gauge_or_railway_is_funicular_p_and_not_tunnel_is_yes_13-18_minor-roads-fill "2">
<!ENTITY q_railway_is_narrow_gauge_or_railway_is_funicular_p_and_tunnel_is_yes_13-18_minor-roads-fill "1.5">
<!ENTITY railway_is_INT_minus_preserved_minus_ssy_12-12_roads "1">
<!ENTITY railway_is_INT_minus_preserved_minus_ssy_13-18_roads "0.8">
<!ENTITY railway_is_INT_minus_spur_minus_siding_minus_yard_13-18_bridges_casing "5.7">
<!ENTITY railway_is_INT_minus_spur_minus_siding_minus_yard_13-18_bridges_casing2 "4">
<!ENTITY railway_is_INT_minus_spur_minus_siding_minus_yard_13-18_bridges_fill "0.8">
<!ENTITY railway_is_light_rail_and_not_tunnel_is_yes_13-18_minor-roads-fill "2">
<!ENTITY railway_is_light_rail_and_tunnel_is_yes_13-18_minor-roads-fill "2">
<!ENTITY railway_is_light_rail_or_railway_is_narrow_gauge_14-18_bridges_casing "5.5">
<!ENTITY railway_is_light_rail_or_railway_is_narrow_gauge_14-18_bridges_casing2 "4">
<!ENTITY railway_is_light_rail_or_railway_is_narrow_gauge_14-18_bridges_fill "2">
<!ENTITY railway_is_miniature_15-18_minor-roads-fill "3">
<!ENTITY railway_is_monorail_14-18_roads "3.0">
<!ENTITY railway_is_preserved_12-12_roads "1.5">
<!ENTITY railway_is_preserved_13-18_roads "1">
<!ENTITY railway_is_rail_13-13_bridges_fill "1">
<!ENTITY railway_is_rail_13-18_bridges_casing "6.5">
<!ENTITY railway_is_rail_13-18_bridges_casing2 "5">
<!ENTITY railway_is_rail_14-18_bridges_fill "1">
<!ENTITY railway_is_rail_6-8_roads "0.6">
<!ENTITY railway_is_rail_and_not_tunnel_is_yes_10-12_roads "2">
<!ENTITY railway_is_rail_and_not_tunnel_is_yes_9-9_roads "1">
<!ENTITY railway_is_rail_and_tunnel_is_yes_10-12_roads "2">
<!ENTITY railway_is_rail_and_tunnel_is_yes_9-9_roads "1">
<!ENTITY railway_is_spur_minus_siding_minus_yard_11-12_minor-roads-fill "1">
<!ENTITY railway_is_spur_minus_siding_minus_yard_and_not_tunnel_is_yes_13-18_minor-roads-fill "0.8">
<!ENTITY railway_is_spur_minus_siding_minus_yard_and_tunnel_is_yes_13-18_minor-roads-fill "2">
<!ENTITY railway_is_subway_14-18_bridges_casing "5.5">
<!ENTITY railway_is_subway_14-18_bridges_casing2 "4">
<!ENTITY railway_is_subway_14-18_bridges_fill "2">
<!ENTITY railway_is_subway_and_not_tunnel_is_yes_12-18_minor-roads-fill "2">
<!ENTITY railway_is_subway_and_tunnel_is_yes_12-18_minor-roads-fill "2">
<!ENTITY railway_is_tram_13-14_trams "1">
<!ENTITY railway_is_tram_and_bridge_is_yes_13-13_guideways "1">
<!ENTITY railway_is_tram_and_bridge_is_yes_14-18_guideways "1">
<!ENTITY railway_is_tram_and_bridge_is_yes_15-18_trams "2">
<!ENTITY railway_is_tram_and_not_bridge_is_yes_15-18_trams "2">
<!ENTITY railway_is_tram_and_tunnel_is_yes_13-14_minor-roads-fill "1">
<!ENTITY railway_is_tram_and_tunnel_is_yes_15-18_minor-roads-fill "2">
<!ENTITY railway_is_tram_or_railway_is_light_rail_or_railway_is_narrow_gauge_or_railway_is_funicular_10-12_roads "1">
<!ENTITY railway_is_tram_or_railway_is_light_rail_or_railway_is_narrow_gauge_or_railway_is_funicular_8-9_roads "1">
<!ENTITY railway_is_turntable_16-18_minor-roads-fill "1.5">
<!ENTITY tracktype_is_grade1_14-18_tracks-notunnel-nobridge "2">
<!ENTITY tracktype_is_grade1_14-18_tracks-tunnels "2">
<!ENTITY tracktype_is_grade2_14-18_tracks-notunnel-nobridge "1.5">
<!ENTITY tracktype_is_grade2_14-18_tracks-tunnels "1.5">
<!ENTITY tracktype_is_grade3_14-18_tracks-notunnel-nobridge "1.5">
<!ENTITY tracktype_is_grade3_14-18_tracks-tunnels "2">
<!ENTITY tracktype_is_grade4_14-18_tracks-notunnel-nobridge "2">
<!ENTITY tracktype_is_grade4_14-18_tracks-tunnels "2">
<!ENTITY tracktype_is_grade5_14-16_waterway-bridges "6">
<!ENTITY tracktype_is_grade5_14-18_tracks-notunnel-nobridge "1.5">
<!ENTITY tracktype_is_grade5_14-18_tracks-tunnels "1.5">
<!ENTITY tracktype_is_grade5_17-18_waterway-bridges "10">
