<!-- ignoring other minor-roads-casing_a_highway__is__residential_or_highway__is__unclassified_or_highway__is__road_z_and_not_tunnel_is_yes: #999 -->
<!-- ignoring other minor-roads-casing_a_highway__is__residential_or_highway__is__unclassified_or_highway__is__road_z_and_not_tunnel_is_yes: #bbb -->
<!-- ignoring other minor-roads-casing_a_highway__is__residential_or_highway__is__unclassified_or_highway__is__road_z_and_not_tunnel_is_yes: #bbb -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #ffffff -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #fdfdfd -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #ececec -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #cacaca -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #afafaf -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #a1a1a1 -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_tunnel__is__yes: #9b9b9b -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_not_tunnel__is__yes: #999999 -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_not_tunnel__is__yes: white -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_not_tunnel__is__yes: #999999 -->
<!-- ignoring minor-roads-fill_railway__is__rail_and_not_tunnel__is__yes: white -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #ffffff -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #fdfdfd -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #ececec -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #cacaca -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #afafaf -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #a1a1a1 -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_tunnel__is__yes: #9b9b9b -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_not_tunnel__is__yes: #999999 -->
<!-- ignoring minor-roads-fill_railway__is__spurminus_sidingminus_yard_and_not_tunnel__is__yes: white -->
<!-- ignoring minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_tunnel_is_yes: #666 -->
<!-- ignoring minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_tunnel_is_yes: #fff -->
<!-- ignoring minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_tunnel_is_yes: #aaa -->
<!-- ignoring minor-roads-fill_highway__is__platform_or_railway__is__platform: grey -->
<!-- ignoring minor-roads-fill_highway__is__platform_or_railway__is__platform: #bbbbbb -->
<!-- ignoring other minor-roads-fill_highway__is__steps: #fff -->
<!-- ignoring other minor-roads-fill_highway__is__steps: salmon -->
<!-- ignoring minor-roads-fill_a_highway__is__cycleway_or_a_highway__is__path_and_bicycle__is__designated_z_z_and_not_tunnel__is__yes: white -->
<!-- ignoring minor-roads-fill_a_highway__is__cycleway_or_a_highway__is__path_and_bicycle__is__designated_z_z_and_not_tunnel__is__yes: blue -->
<!-- ignoring other guideways_railway__is__tram_and_bridge_is_yes: white -->
<!-- ignoring other guideways_railway__is__tram_and_bridge_is_yes: #6666ff -->
<!-- ignoring other guideways_railway__is__tram_and_bridge_is_yes: white -->
<!ENTITY access_a_access__is__private_or_access__is__no_z_and_a_highway__is__service_and_not_service__is__INTminus_minor_z "#efa9a9">
<!ENTITY access_a_access__is__private_or_access__is__no_z_and_not_highway__is__service "#efa9a9">
<!ENTITY access_access__is__permissive_and_a_highway__is__service_and_not_service__is__INTminus_minor_z "#cf9">
<!ENTITY access_access__is__permissive_and_a_highway_is_unclassified_or_highway_is_residential_or_highway_is_footway_or_highway_is_service_z "#cf9">
<!ENTITY access_access__is__permissive_and_a_highway_is_unclassified_or_highway_is_residential_or_highway_is_footway_z "#cf9">
<!ENTITY access_access__is__private_or_access__is__no "#efa9a9">
<!ENTITY access_access_is_destination_and_a_highway__is__service_and_not_service__is__INTminus_minor_z "#c2e0ff">
<!ENTITY access_access_is_destination_and_a_highway_is_unclassified_or_highway_is_residential_or_highway_is_service_z "#c2e0ff">
<!ENTITY access_access_is_destination_and_a_highway_is_unclassified_or_highway_is_residential_z "#c2e0ff">
<!ENTITY barriers_area_barrier__isnot__empty_and_not_barrier__is__hedge "#444">
<!ENTITY barriers_barrier__is__embankment "#444">
<!ENTITY barriers_barrier__isnot__empty_and_not_a_barrier__is__hedge_or_barrier__is__embankment_z "#444">
<!ENTITY barriers_natural_is_hedge_or_barrier__is__hedge "#aed1a0">
<!ENTITY boundary_oneway__is__minus_1 "green">
<!ENTITY bridges_casing2_a_railway__is__disused_or_railway__is__abandoned_or_railway_is_construction_z_and_not_highway__isnot__empty "white">
<!ENTITY bridges_casing2_highway__is__bridleway_or_a_highway__is__path_and_horse__is__designated_z "white">
<!ENTITY bridges_casing2_highway__is__byway "white">
<!ENTITY bridges_casing2_highway__is__cycleway_or_a_highway__is__path_and_bicycle__is__designated_z "white">
<!ENTITY bridges_casing2_highway__is__footway_or_a_highway__is__path_and_foot__is__designated_z "white">
<!ENTITY bridges_casing2_highway__is__path_and_not_a_bicycle__is__designated_or_foot__is__designated_or_horse__is__designated_z "white">
<!ENTITY bridges_casing2_highway__is__track_and_not_tracktype__isnot__empty "white">
<!ENTITY bridges_casing2_highway__is__track_and_tracktype__is__grade1 "white">
<!ENTITY bridges_casing2_highway__is__track_and_tracktype__is__grade2 "white">
<!ENTITY bridges_casing2_highway__is__track_and_tracktype__is__grade3 "white">
<!ENTITY bridges_casing2_highway__is__track_and_tracktype__is__grade4 "white">
<!ENTITY bridges_casing2_highway__is__track_and_tracktype__is__grade5 "white">
<!ENTITY bridges_casing2_highway__is__unsurfaced "white">
<!ENTITY bridges_casing2_railway__is__INTminus_spurminus_sidingminus_yard "white">
<!ENTITY bridges_casing2_railway__is__rail "white">
<!ENTITY bridges_casing2_railway_is_light_rail_or_railway_is_narrow_gauge "white">
<!ENTITY bridges_casing2_railway_is_subway "white">
<!ENTITY bridges_casing_a_railway__is__disused_or_railway__is__abandoned_or_railway_is_construction_z_and_not_highway__isnot__empty "black">
<!ENTITY bridges_casing_aeroway__is__runway "black">
<!ENTITY bridges_casing_aeroway__is__taxiway "black">
<!ENTITY bridges_casing_highway__is__bridleway_or_a_highway__is__path_and_horse__is__designated_z "black">
<!ENTITY bridges_casing_highway__is__byway "black">
<!ENTITY bridges_casing_highway__is__cycleway_or_a_highway__is__path_and_bicycle__is__designated_z "black">
<!ENTITY bridges_casing_highway__is__footway_or_a_highway__is__path_and_foot__is__designated_z "black">
<!ENTITY bridges_casing_highway__is__motorway_or_highway_is_motorway_link "black">
<!ENTITY bridges_casing_highway__is__path_and_not_a_bicycle__is__designated_or_foot__is__designated_or_horse__is__designated_z "black">
<!ENTITY bridges_casing_highway__is__pedestrian "black">
<!ENTITY bridges_casing_highway__is__primary_or_highway_is_primary_link "black">
<!ENTITY bridges_casing_highway__is__residential_or_highway__is__unclassified_or_highway__is__road "black">
<!ENTITY bridges_casing_highway__is__secondary_or_highway_is_secondary_link "black">
<!ENTITY bridges_casing_highway__is__service "black">
<!ENTITY bridges_casing_highway__is__tertiary_or_highway_is_tertiary_link "black">
<!ENTITY bridges_casing_highway__is__track_and_not_tracktype__isnot__empty "black">
<!ENTITY bridges_casing_highway__is__track_and_tracktype__is__grade1 "black">
<!ENTITY bridges_casing_highway__is__track_and_tracktype__is__grade2 "black">
<!ENTITY bridges_casing_highway__is__track_and_tracktype__is__grade3 "black">
<!ENTITY bridges_casing_highway__is__track_and_tracktype__is__grade4 "black">
<!ENTITY bridges_casing_highway__is__track_and_tracktype__is__grade5 "black">
<!ENTITY bridges_casing_highway__is__trunk_or_highway_is_trunk_link "black">
<!ENTITY bridges_casing_highway__is__unsurfaced "black">
<!ENTITY bridges_casing_railway__is__INTminus_spurminus_sidingminus_yard "black">
<!ENTITY bridges_casing_railway__is__rail "black">
<!ENTITY bridges_casing_railway_is_light_rail_or_railway_is_narrow_gauge "#555">
<!ENTITY bridges_casing_railway_is_subway "black">
<!ENTITY bridges_fill_a_railway__is__disused_or_railway__is__abandoned_or_railway_is_construction_z_and_not_highway__isnot__empty "grey">
<!ENTITY bridges_fill_aeroway__is__runway "#bbc">
<!ENTITY bridges_fill_aeroway__is__taxiway "#bbc">
<!ENTITY bridges_fill_highway__is__bridleway_or_a_highway__is__path_and_horse__is__designated_z "green">
<!ENTITY bridges_fill_highway__is__byway "#ffcc00">
<!ENTITY bridges_fill_highway__is__cycleway_or_a_highway__is__path_and_bicycle__is__designated_z "blue">
<!ENTITY bridges_fill_highway__is__footway_or_a_highway__is__path_and_foot__is__designated_z "salmon">
<!ENTITY bridges_fill_highway__is__motorway_or_highway_is_motorway_link "#809bc0">
<!ENTITY bridges_fill_highway__is__path_and_not_a_bicycle__is__designated_or_foot__is__designated_or_horse__is__designated_z "black">
<!ENTITY bridges_fill_highway__is__pedestrian "#ededed">
<!ENTITY bridges_fill_highway__is__primary_or_highway_is_primary_link "#ec989a">
<!ENTITY bridges_fill_highway__is__residential_or_highway__is__unclassified "white">
<!ENTITY bridges_fill_highway__is__road "#ddd">
<!ENTITY bridges_fill_highway__is__secondary_or_highway__is__secondary_link "#fed7a5">
<!ENTITY bridges_fill_highway__is__service "white">
<!ENTITY bridges_fill_highway__is__tertiary_or_highway_is_tertiary_link "#ffffb3">
<!ENTITY bridges_fill_highway__is__track_and_not_tracktype__isnot__empty "#996600">
<!ENTITY bridges_fill_highway__is__track_and_tracktype__is__grade1 "#b37700">
<!ENTITY bridges_fill_highway__is__track_and_tracktype__is__grade2 "#a87000">
<!ENTITY bridges_fill_highway__is__track_and_tracktype__is__grade3 "#996600">
<!ENTITY bridges_fill_highway__is__track_and_tracktype__is__grade4 "#996600">
<!ENTITY bridges_fill_highway__is__track_and_tracktype__is__grade5 "#996600">
<!ENTITY bridges_fill_highway__is__trunk_or_highway_is_trunk_link "#a9dba9">
<!ENTITY bridges_fill_highway__is__unsurfaced "#debd9c">
<!ENTITY bridges_fill_railway__is__INTminus_spurminus_sidingminus_yard "white">
<!ENTITY bridges_fill_railway__is__rail "white">
<!ENTITY bridges_fill_railway_is_light_rail_or_railway_is_narrow_gauge "#666">
<!ENTITY bridges_fill_railway_is_subway "#999">
<!ENTITY directions_oneway__is__minus_1 "#6c70d5">
<!ENTITY directions_oneway__is__yes "#6c70d5">
<!ENTITY footbikecycle-tunnels_highway__is__bridleway_or_a_highway__is__path_and_horse__is__designated_z "green">
<!ENTITY footbikecycle-tunnels_highway__is__cycleway_or_a_highway__is__path_and_bicycle__is__designated_z "blue">
<!ENTITY footbikecycle-tunnels_highway__is__footway_or_a_highway__is__path_and_foot__is__designated_z "salmon">
<!ENTITY footbikecycle-tunnels_highway__is__path_and_not_a_bicycle__is__designated_or_foot__is__designated_or_horse__is__designated_z "black">
<!ENTITY guideways_railway__is__tram_and_bridge_is_yes "#6666ff">
<!ENTITY highway-area-casing_highway__is__pedestrian_or_highway_is_service_or_highway_is_footway_or_highway_is_path "grey">
<!ENTITY highway-area-casing_highway__is__platform_or_railway__is__platform "grey">
<!ENTITY highway-area-casing_highway__is__residential_or_highway_is_unclassified "#999">
<!ENTITY highway-area-casing_highway__is__track "#996600">
<!ENTITY landuse_overlay_landuse_is_military "#f55">
<!ENTITY landuse_overlay_leisure__is__nature_reserve "#6c3">
<!ENTITY minor-roads-casing-links_highway__is__primary_link_and_not_tunnel__is__yes "#8d4346">
<!ENTITY minor-roads-casing-links_highway__is__secondary_link_and_not_tunnel__is__yes "#a37b48">
<!ENTITY minor-roads-casing-links_highway__is__tertiary_link_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing-links_highway__is__trunk_link_and_not_tunnel__is__yes "#477147">
<!ENTITY minor-roads-casing-links_highway_is_motorway_link_and_not_tunnel__is__yes "#506077">
<!ENTITY minor-roads-casing-links_highway_is_raceway "pink">
<!ENTITY minor-roads-casing_a_highway__is__residential_or_highway__is__unclassified_or_highway__is__road_z_and_not_tunnel_is_yes "#999">
<!ENTITY minor-roads-casing_a_highway__is__tertiary_or_highway__is__residential_or_highway__is__unclassified_or_highway__is__road_z_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_highway__is__living_street "white">
<!ENTITY minor-roads-casing_highway__is__motorway_and_not_tunnel__is__yes "#506077">
<!ENTITY minor-roads-casing_highway__is__pedestrian_and_not_tunnel_is_yes "grey">
<!ENTITY minor-roads-casing_highway__is__pedestrian_and_tunnel_is_yes "grey">
<!ENTITY minor-roads-casing_highway__is__primary_and_not_tunnel__is__yes "#8d4346">
<!ENTITY minor-roads-casing_highway__is__secondary_and_not_tunnel__is__yes "#a37b48">
<!ENTITY minor-roads-casing_highway__is__service_and_not_a_service_is_INTminus_minor_or_tunnel_is_yes_z "#999">
<!ENTITY minor-roads-casing_highway__is__service_and_service_is_INTminus_minor "#999">
<!ENTITY minor-roads-casing_highway__is__service_and_tunnel_is_yes "#999">
<!ENTITY minor-roads-casing_highway__is__tertiary_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_highway__is__trunk_and_not_tunnel__is__yes "#477147">
<!ENTITY minor-roads-fill-links_highway__is__motorway_link_and_not_tunnel__is__yes "#809bc0">
<!ENTITY minor-roads-fill-links_highway__is__primary_link_and_not_tunnel__is__yes "#ec989a">
<!ENTITY minor-roads-fill-links_highway__is__secondary_link_and_not_tunnel_is_yes "#fed7a5">
<!ENTITY minor-roads-fill-links_highway__is__tertiary_link_and_not_tunnel_is_yes "#ffffb3">
<!ENTITY minor-roads-fill-links_highway__is__trunk_link_and_not_tunnel__is__yes "#a9dba9">
<!ENTITY minor-roads-fill-links_highway_is_motorway_link_and_not_tunnel__is__yes "#809bc0">
<!ENTITY minor-roads-fill_a_highway__is__bridleway_or_a_highway__is__path_and_horse__is__designated_z_z_and_not_tunnel_is_yes "green">
<!ENTITY minor-roads-fill_a_highway__is__footway_or_a_highway__is__path_and_foot__is__designated_z_z_and_not_tunnel_is_yes "salmon">
<!ENTITY minor-roads-fill_a_highway__is__residential_or_highway__is__unclassified_z_and_not_tunnel__is__yes "#fff">
<!ENTITY minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_not_tunnel_is_yes "#666">
<!ENTITY minor-roads-fill_aeroway__is__runway "#bbc">
<!ENTITY minor-roads-fill_aeroway__is__runway_and_not_bridge_is_yes "#bbc">
<!ENTITY minor-roads-fill_aeroway__is__taxiway "#bbc">
<!ENTITY minor-roads-fill_aeroway__is__taxiway_and_not_bridge_is_yes "#bbc">
<!ENTITY minor-roads-fill_highway__is__living_street "#ccc">
<!ENTITY minor-roads-fill_highway__is__motorway_and_not_tunnel__is__yes "#809bc0">
<!ENTITY minor-roads-fill_highway__is__path_and_not_a_bicycle__is__designated_or_foot__is__designated_or_horse__is__designated_z_and_not_tunnel__is__yes "black">
<!ENTITY minor-roads-fill_highway__is__pedestrian "#ededed">
<!ENTITY minor-roads-fill_highway__is__primary_and_not_tunnel__is__yes "#ec989a">
<!ENTITY minor-roads-fill_highway__is__road "#ddd">
<!ENTITY minor-roads-fill_highway__is__secondary_and_not_tunnel_is_yes "#fed7a5">
<!ENTITY minor-roads-fill_highway__is__service_and_not_service_is_INTminus_minor "white">
<!ENTITY minor-roads-fill_highway__is__service_and_service_is_INTminus_minor "#fff">
<!ENTITY minor-roads-fill_highway__is__steps "salmon">
<!ENTITY minor-roads-fill_highway__is__tertiary_and_not_tunnel_is_yes "#ffffb3">
<!ENTITY minor-roads-fill_highway__is__tertiary_or_highway__is__residential_or_highway__is__unclassified_or_highway__is__road "#bbb">
<!ENTITY minor-roads-fill_highway__is__track "#996600">
<!ENTITY minor-roads-fill_highway__is__trunk_and_not_tunnel__is__yes "#a9dba9">
<!ENTITY minor-roads-fill_highway__is__unsurfaced "#debd9c">
<!ENTITY minor-roads-fill_railway__is__spurminus_sidingminus_yard "#aaa">
<!ENTITY minor-roads-fill_railway__is__turntable "#999">
<!ENTITY minor-roads-fill_railway_is_light_rail_and_not_tunnel__is__yes "#666">
<!ENTITY minor-roads-fill_railway_is_light_rail_and_tunnel__is__yes "#666">
<!ENTITY minor-roads-fill_railway_is_miniature "#999">
<!ENTITY minor-roads-fill_railway_is_subway_and_not_tunnel__is__yes "#999">
<!ENTITY minor-roads-fill_railway_is_subway_and_tunnel__is__yes "#999">
<!ENTITY minor-roads-fill_railway_is_tram_and_tunnel_is_yes "#444">
<!ENTITY roads_highway__is__motorway_or_highway__is__motorway_link "#809bc0">
<!ENTITY roads_highway__is__primary_or_highway__is__primary_link "#ec989a">
<!ENTITY roads_highway__is__secondary_or_highway__is__secondary_link "#fecc8b">
<!ENTITY roads_highway__is__trunk_or_highway__is__trunk_link "#97d397">
<!ENTITY roads_railway__is__INTminus_preservedminus_ssy "white">
<!ENTITY roads_railway__is__preserved "white">
<!ENTITY roads_railway__is__rail "#aaa">
<!ENTITY roads_railway__is__rail_and_not_tunnel_is_yes "#aaa">
<!ENTITY roads_railway__is__rail_and_tunnel_is_yes "#aaa">
<!ENTITY roads_railway__is__tram_or_railway__is__light_rail_or_railway__is__narrow_gauge_or_railway_is_funicular "#aaa">
<!ENTITY roads_railway_is_monorail "#777">
<!ENTITY theme_park_tourism_is_theme_park "#734a08">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade1 "#b37700">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade2 "#a87000">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade3 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade4 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "#b37700">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "#a87000">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#996600">
<!ENTITY trams_railway__is__tram "#444">
<!ENTITY trams_railway__is__tram_and_bridge_is_yes "#444">
<!ENTITY trams_railway__is__tram_and_not_bridge_is_yes "#444">
<!ENTITY tunnels-casing_highway__is__motorway_or_highway_is_motorway_link "#506077">
<!ENTITY tunnels-casing_highway__is__primary_or_highway__is__primary_link "#8d4346">
<!ENTITY tunnels-casing_highway__is__residential_or_highway__is__unclassified_or_highway__is__road "#999">
<!ENTITY tunnels-casing_highway__is__secondary_or_highway__is__secondary_link "#a37b48">
<!ENTITY tunnels-casing_highway__is__tertiary_or_highway_is_tertiary_link "#999">
<!ENTITY tunnels-casing_highway__is__tertiary_or_highway_is_tertiary_link_or_highway__is__residential_or_highway__is__unclassified_or_highway__is__road "#999">
<!ENTITY tunnels-casing_highway__is__trunk_or_highway__is__trunk_link "#477147">
<!ENTITY tunnels-fill_highway__is__motorway_or_highway__is__motorway_link "#d6dfea">
<!ENTITY tunnels-fill_highway__is__motorway_or_highway_is_motorway_link "#d6dfea">
<!ENTITY tunnels-fill_highway__is__primary_or_highway__is__primary_link "#f4c3c4">
<!ENTITY tunnels-fill_highway__is__residential_or_highway__is__unclassified_or_highway__is__road "#fff">
<!ENTITY tunnels-fill_highway__is__secondary_or_highway__is__secondary_link "#fee0b8">
<!ENTITY tunnels-fill_highway__is__tertiary_or_highway_is_tertiary_link "#ffc">
<!ENTITY tunnels-fill_highway__is__trunk_or_highway__is__trunk_link "#cdeacd">
<!ENTITY waterway-bridges_tracktype_is_grade5 "#b5d0d0">
