<!-- ignoring other minor-roads-casing_a_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_z_and_not_tunnel_is_yes: #999 -->
<!-- ignoring other minor-roads-casing_a_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_z_and_not_tunnel_is_yes: #bbb -->
<!-- ignoring other minor-roads-casing_a_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_z_and_not_tunnel_is_yes: #bbb -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #ffffff -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #fdfdfd -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #ececec -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #cacaca -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #afafaf -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #a1a1a1 -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_tunnel_is_yes: #9b9b9b -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: #999999 -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: white -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: #999999 -->
<!-- ignoring minor-roads-fill_railway_is_rail_and_not_tunnel_is_yes: white -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #ffffff -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #fdfdfd -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #ececec -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #cacaca -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #afafaf -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #a1a1a1 -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_tunnel_is_yes: #9b9b9b -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_not_tunnel_is_yes: #999999 -->
<!-- ignoring minor-roads-fill_railway_is_spurminus_sidingminus_yard_and_not_tunnel_is_yes: white -->
<!-- ignoring minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_tunnel_is_yes: #666 -->
<!-- ignoring minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_tunnel_is_yes: #fff -->
<!-- ignoring minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_tunnel_is_yes: #aaa -->
<!-- ignoring minor-roads-fill_highway_is_platform_or_railway_is_platform: grey -->
<!-- ignoring minor-roads-fill_highway_is_platform_or_railway_is_platform: #bbbbbb -->
<!-- ignoring other minor-roads-fill_highway_is_steps: #fff -->
<!-- ignoring other minor-roads-fill_highway_is_steps: salmon -->
<!-- ignoring minor-roads-fill_a_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z_z_and_not_tunnel_is_yes: white -->
<!-- ignoring minor-roads-fill_a_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z_z_and_not_tunnel_is_yes: blue -->
<!-- ignoring other guideways_railway_is_tram_and_bridge_is_yes: white -->
<!-- ignoring other guideways_railway_is_tram_and_bridge_is_yes: #6666ff -->
<!-- ignoring other guideways_railway_is_tram_and_bridge_is_yes: white -->

<!-- motorway -->
<!-- #506077 -->
<!ENTITY tunnels-casing_highway_is_motorway_or_highway_is_motorway_link "#000">
<!ENTITY minor-roads-casing-links_highway_is_motorway_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_motorway_and_not_tunnel_is_yes "#000">
<!ENTITY bridges_casing_highway_is_motorway_or_highway_is_motorway_link "#000">

<!-- #809bc0 -->
<!ENTITY minor-roads-fill-links_highway_is_motorway_link_and_not_tunnel_is_yes "#3f3f7f">
<!ENTITY minor-roads-fill_highway_is_motorway_and_not_tunnel_is_yes "#3f3f7f">
<!ENTITY bridges_fill_highway_is_motorway_or_highway_is_motorway_link "#3f3f7f">
<!ENTITY roads_highway_is_motorway_or_highway_is_motorway_link "#3f3f7f">

<!-- #d6dfea -->
<!ENTITY tunnels-fill_highway_is_motorway_or_highway_is_motorway_link "#6f6faf">


<!-- trunk -->
<!-- #477147 -->
<!ENTITY tunnels-casing_highway_is_trunk_or_highway_is_trunk_link "#000">
<!ENTITY minor-roads-casing-links_highway_is_trunk_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_trunk_and_not_tunnel_is_yes "#000">
<!ENTITY bridges_casing_highway_is_trunk_or_highway_is_trunk_link "#000">

<!-- #a9dba9 -->
<!ENTITY minor-roads-fill-links_highway_is_trunk_link_and_not_tunnel_is_yes "#7f3f7f">
<!ENTITY minor-roads-fill_highway_is_trunk_and_not_tunnel_is_yes "#7f3f7f">
<!ENTITY bridges_fill_highway_is_trunk_or_highway_is_trunk_link "#7f3f7f">
<!ENTITY roads_highway_is_trunk_or_highway_is_trunk_link "#7f3f7f">

<!-- #cdeacd -->
<!ENTITY tunnels-fill_highway_is_trunk_or_highway_is_trunk_link "#af6faf">


<!-- primary -->
<!-- #8d4346 -->
<!ENTITY tunnels-casing_highway_is_primary_or_highway_is_primary_link "#000">
<!ENTITY minor-roads-casing-links_highway_is_primary_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_primary_and_not_tunnel_is_yes "#000">
<!ENTITY bridges_casing_highway_is_primary_or_highway_is_primary_link "#000">

<!-- #ec989a -->
<!ENTITY minor-roads-fill-links_highway_is_primary_link_and_not_tunnel_is_yes "#7f0000">
<!ENTITY minor-roads-fill_highway_is_primary_and_not_tunnel_is_yes "#7f0000">
<!ENTITY bridges_fill_highway_is_primary_or_highway_is_primary_link "#7f0000">
<!ENTITY roads_highway_is_primary_or_highway_is_primary_link "#7f0000">

<!-- #f4c3c4 -->
<!ENTITY tunnels-fill_highway_is_primary_or_highway_is_primary_link "#af3030">


<!-- secondary -->
<!-- #a37b48 -->
<!ENTITY tunnels-casing_highway_is_secondary_or_highway_is_secondary_link "#000">
<!ENTITY minor-roads-casing-links_highway_is_secondary_link_and_not_tunnel_is_yes "#000">
<!ENTITY minor-roads-casing_highway_is_secondary_and_not_tunnel_is_yes "#000">

<!-- #fed7a5 -->
<!ENTITY minor-roads-fill-links_highway_is_secondary_link_and_not_tunnel_is_yes "#7f7f00">
<!ENTITY minor-roads-fill_highway_is_secondary_and_not_tunnel_is_yes "#7f7f00">
<!ENTITY bridges_fill_highway_is_secondary_or_highway_is_secondary_link "#7f7f00">
<!-- #fecc8b -->
<!ENTITY roads_highway_is_secondary_or_highway_is_secondary_link "#7f7f00">

<!-- #fee0b8 -->
<!ENTITY tunnels-fill_highway_is_secondary_or_highway_is_secondary_link "#afaf30">


<!-- tertiary -->
<!-- #ffffb3 -->
<!ENTITY minor-roads-fill-links_highway_is_tertiary_link_and_not_tunnel_is_yes "#bfbfbf">
<!ENTITY minor-roads-fill_highway_is_tertiary_and_not_tunnel_is_yes "#bfbfbf">
<!ENTITY bridges_fill_highway_is_tertiary_or_highway_is_tertiary_link "#bfbfbf">

<!-- #ffc -->
<!ENTITY tunnels-fill_highway_is_tertiary_or_highway_is_tertiary_link "#efefef">


<!-- #000 -->
<!ENTITY waterway-bridges_tracktype_is_grade5 "#000">

<!-- #444 -->
<!ENTITY minor-roads-fill_railway_is_tram_and_tunnel_is_yes "#444">
<!ENTITY trams_railway_is_tram "#444">
<!ENTITY trams_railway_is_tram_and_not_bridge_is_yes "#444">
<!ENTITY trams_railway_is_tram_and_bridge_is_yes "#444">
<!ENTITY barriers_area_barrier_isnot_empty_and_not_barrier_is_hedge "#444">
<!ENTITY barriers_barrier_is_embankment "#444">
<!ENTITY barriers_barrier_isnot_empty_and_not_a_barrier_is_hedge_or_barrier_is_embankment_z "#444">

<!-- #555 -->
<!ENTITY bridges_casing_railway_is_light_rail_or_railway_is_narrow_gauge "#555">

<!-- #666 -->
<!ENTITY minor-roads-fill_a_railway_is_narrow_gauge_or_railway_is_funicular_z_and_not_tunnel_is_yes "#666">
<!ENTITY minor-roads-fill_railway_is_light_rail_and_tunnel_is_yes "#666">
<!ENTITY minor-roads-fill_railway_is_light_rail_and_not_tunnel_is_yes "#666">
<!ENTITY bridges_fill_railway_is_light_rail_or_railway_is_narrow_gauge "#666">

<!-- #6666ff -->
<!ENTITY guideways_railway_is_tram_and_bridge_is_yes "#6666ff">

<!-- #6c3 -->
<!ENTITY landuse_overlay_leisure_is_nature_reserve "#6c3">

<!-- #6c70d5 -->
<!ENTITY directions_oneway_is_yes "#6c70d5">
<!ENTITY directions_oneway_is_minus_1 "#6c70d5">

<!-- #734a08 -->
<!ENTITY theme_park_tourism_is_theme_park "#734a08">

<!-- #777 -->
<!ENTITY roads_railway_is_monorail "#777">

<!-- #996600 -->
<!ENTITY highway-area-casing_highway_is_track "#996600">
<!ENTITY minor-roads-fill_highway_is_track "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade3 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade4 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#996600">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#996600">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade3 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade4 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade5 "#996600">
<!ENTITY bridges_fill_highway_is_track_and_not_tracktype_isnot_empty "#996600">

<!-- #999 -->
<!ENTITY highway-area-casing_highway_is_residential_or_highway_is_unclassified "#999">
<!ENTITY tunnels-casing_highway_is_tertiary_or_highway_is_tertiary_link "#999">
<!ENTITY tunnels-casing_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#999">
<!ENTITY tunnels-casing_highway_is_tertiary_or_highway_is_tertiary_link_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#999">
<!ENTITY minor-roads-casing_a_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_z_and_not_tunnel_is_yes "#999">
<!ENTITY minor-roads-casing_highway_is_service_and_not_a_service_is_INTminus_minor_or_tunnel_is_yes_z "#999">
<!ENTITY minor-roads-casing_highway_is_service_and_tunnel_is_yes "#999">
<!ENTITY minor-roads-casing_highway_is_service_and_service_is_INTminus_minor "#999">
<!ENTITY minor-roads-fill_railway_is_miniature "#999">
<!ENTITY minor-roads-fill_railway_is_subway_and_tunnel_is_yes "#999">
<!ENTITY minor-roads-fill_railway_is_subway_and_not_tunnel_is_yes "#999">
<!ENTITY minor-roads-fill_railway_is_turntable "#999">
<!ENTITY bridges_fill_railway_is_subway "#999">

<!-- #999999 -->
<!ENTITY bridges_fill_railway_is_rail "#999999">
<!ENTITY bridges_fill_railway_is_rail "#999999">
<!ENTITY bridges_fill_railway_is_INTminus_spurminus_sidingminus_yard "#999999">
<!ENTITY roads_railway_is_preserved "#999999">
<!ENTITY roads_railway_is_INTminus_preservedminus_ssy "#999999">

<!-- #a87000 -->
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade2 "#a87000">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "#a87000">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade2 "#a87000">

<!-- #aaa -->
<!ENTITY minor-roads-fill_railway_is_spurminus_sidingminus_yard "#aaa">
<!ENTITY roads_railway_is_rail "#aaa">
<!ENTITY roads_railway_is_rail_and_not_tunnel_is_yes "#aaa">
<!ENTITY roads_railway_is_rail_and_tunnel_is_yes "#aaa">
<!ENTITY roads_railway_is_tram_or_railway_is_light_rail_or_railway_is_narrow_gauge_or_railway_is_funicular "#aaa">
<!ENTITY roads_railway_is_preserved "#aaa">
<!ENTITY roads_railway_is_INTminus_preservedminus_ssy "#aaa">

<!-- #aed1a0 -->
<!ENTITY barriers_natural_is_hedge_or_barrier_is_hedge "#aed1a0">

<!-- #b37700 -->
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade1 "#b37700">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "#b37700">
<!ENTITY bridges_fill_highway_is_track_and_tracktype_is_grade1 "#b37700">

<!-- #b5d0d0 -->
<!ENTITY waterway-bridges_tracktype_is_grade5 "#b5d0d0">
<!ENTITY waterway-bridges_tracktype_is_grade5 "#b5d0d0">

<!-- #bbb -->
<!ENTITY minor-roads-casing-links_highway_is_tertiary_link_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_highway_is_tertiary_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-casing_a_highway_is_tertiary_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road_z_and_not_tunnel_is_yes "#bbb">
<!ENTITY minor-roads-fill_highway_is_tertiary_or_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#bbb">

<!-- #bbbbbb -->
<!ENTITY minor-roads-fill_highway_is_service_and_not_service_is_INTminus_minor "#bbbbbb">

<!-- #bbc -->
<!ENTITY minor-roads-fill_aeroway_is_runway "#bbc">
<!ENTITY minor-roads-fill_aeroway_is_runway_and_not_bridge_is_yes "#bbc">
<!ENTITY minor-roads-fill_aeroway_is_taxiway "#bbc">
<!ENTITY minor-roads-fill_aeroway_is_taxiway_and_not_bridge_is_yes "#bbc">
<!ENTITY bridges_fill_aeroway_is_runway "#bbc">
<!ENTITY bridges_fill_aeroway_is_taxiway "#bbc">

<!-- #c2e0ff -->
<!ENTITY access_access_is_destination_and_a_highway_is_unclassified_or_highway_is_residential_z "#c2e0ff">
<!ENTITY access_access_is_destination_and_a_highway_is_service_and_not_service_is_INTminus_minor_z "#c2e0ff">
<!ENTITY access_access_is_destination_and_a_highway_is_unclassified_or_highway_is_residential_or_highway_is_service_z "#c2e0ff">

<!-- #ccc -->
<!ENTITY minor-roads-fill_highway_is_living_street "#ccc">
<!ENTITY roads_railway_is_tram_or_railway_is_light_rail_or_railway_is_narrow_gauge_or_railway_is_funicular "#ccc">

<!-- #cf9 -->
<!ENTITY access_access_is_permissive_and_a_highway_is_unclassified_or_highway_is_residential_or_highway_is_footway_z "#cf9">
<!ENTITY access_access_is_permissive_and_a_highway_is_service_and_not_service_is_INTminus_minor_z "#cf9">
<!ENTITY access_access_is_permissive_and_a_highway_is_unclassified_or_highway_is_residential_or_highway_is_footway_or_highway_is_service_z "#cf9">

<!-- #ddd -->
<!ENTITY minor-roads-fill_highway_is_road "#ddd">
<!ENTITY bridges_fill_highway_is_road "#ddd">

<!-- #debd9c -->
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#debd9c">
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#debd9c">
<!ENTITY bridges_fill_highway_is_unsurfaced "#debd9c">

<!-- #ededed -->
<!ENTITY minor-roads-fill_highway_is_pedestrian "#ededed">
<!ENTITY bridges_fill_highway_is_pedestrian "#ededed">

<!-- #efa9a9 -->
<!ENTITY access_a_access_is_private_or_access_is_no_z_and_not_highway_is_service "#efa9a9">
<!ENTITY access_a_access_is_private_or_access_is_no_z_and_a_highway_is_service_and_not_service_is_INTminus_minor_z "#efa9a9">
<!ENTITY access_access_is_private_or_access_is_no "#efa9a9">

<!-- #f55 -->
<!ENTITY landuse_overlay_landuse_is_military "#f55">

<!-- #ffcc00 -->
<!ENTITY bridges_fill_highway_is_byway "#ffcc00">

<!-- #fff -->
<!ENTITY tunnels-fill_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#fff">
<!ENTITY minor-roads-fill_a_highway_is_residential_or_highway_is_unclassified_z_and_not_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_highway_is_service_and_service_is_INTminus_minor "#fff">
<!ENTITY minor-roads-fill_a_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z_z_and_not_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_a_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z_z_and_not_tunnel_is_yes "#fff">
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#fff">
<!ENTITY minor-roads-fill_highway_is_unsurfaced "#fff">
<!ENTITY footbikecycle-tunnels_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z "#fff">
<!ENTITY footbikecycle-tunnels_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z "#fff">
<!ENTITY roads_railway_is_monorail "#fff">

<!-- #000 -->
<!ENTITY minor-roads-fill_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z_and_not_tunnel_is_yes "#000">
<!ENTITY footbikecycle-tunnels_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z "#000">
<!ENTITY bridges_casing_highway_is_motorway_or_highway_is_motorway_link "#000">
<!ENTITY bridges_casing_highway_is_trunk_or_highway_is_trunk_link "#000">
<!ENTITY bridges_casing_highway_is_primary_or_highway_is_primary_link "#000">
<!ENTITY bridges_casing_highway_is_secondary_or_highway_is_secondary_link "#000">
<!ENTITY bridges_casing_highway_is_tertiary_or_highway_is_tertiary_link "#000">
<!ENTITY bridges_casing_highway_is_residential_or_highway_is_unclassified_or_highway_is_road "#000">
<!ENTITY bridges_casing_highway_is_service "#000">
<!ENTITY bridges_casing_highway_is_pedestrian "#000">
<!ENTITY bridges_casing_aeroway_is_runway "#000">
<!ENTITY bridges_casing_aeroway_is_taxiway "#000">
<!ENTITY bridges_casing_railway_is_subway "#000">
<!ENTITY bridges_casing_highway_is_unsurfaced "#000">
<!ENTITY bridges_casing_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z "#000">
<!ENTITY bridges_casing_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z "#000">
<!ENTITY bridges_casing_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z "#000">
<!ENTITY bridges_casing_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z "#000">
<!ENTITY bridges_casing_highway_is_byway "#000">
<!ENTITY bridges_casing_railway_is_rail "#000">
<!ENTITY bridges_casing_railway_is_INTminus_spurminus_sidingminus_yard "#000">
<!ENTITY bridges_casing_a_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_z_and_not_highway_isnot_empty "#000">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade1 "#000">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade2 "#000">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade3 "#000">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade4 "#000">
<!ENTITY bridges_casing_highway_is_track_and_tracktype_is_grade5 "#000">
<!ENTITY bridges_casing_highway_is_track_and_not_tracktype_isnot_empty "#000">
<!ENTITY bridges_fill_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z "#000">
<!ENTITY trams_railway_is_tram_and_bridge_is_yes "#000">

<!-- blue -->
<!ENTITY footbikecycle-tunnels_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z "blue">
<!ENTITY bridges_fill_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z "blue">

<!-- green -->
<!ENTITY minor-roads-fill_a_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z_z_and_not_tunnel_is_yes "green">
<!ENTITY footbikecycle-tunnels_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z "green">
<!ENTITY bridges_fill_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z "green">
<!ENTITY boundary_oneway_is_minus_1 "green">

<!-- grey -->
<!ENTITY highway-area-casing_highway_is_pedestrian_or_highway_is_service_or_highway_is_footway_or_highway_is_path "grey">
<!ENTITY highway-area-casing_highway_is_platform_or_railway_is_platform "grey">
<!ENTITY minor-roads-casing_highway_is_pedestrian_and_not_tunnel_is_yes "grey">
<!ENTITY minor-roads-casing_highway_is_pedestrian_and_tunnel_is_yes "grey">
<!ENTITY footbikecycle-tunnels_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z "grey">
<!ENTITY footbikecycle-tunnels_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z "grey">
<!ENTITY footbikecycle-tunnels_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z "grey">
<!ENTITY footbikecycle-tunnels_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "grey">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "grey">
<!ENTITY bridges_fill_a_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_z_and_not_highway_isnot_empty "grey">

<!-- pink -->
<!ENTITY minor-roads-casing-links_highway_is_raceway "pink">

<!-- salmon -->
<!ENTITY minor-roads-fill_highway_is_steps "salmon">
<!ENTITY minor-roads-fill_a_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z_z_and_not_tunnel_is_yes "salmon">
<!ENTITY footbikecycle-tunnels_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z "salmon">
<!ENTITY bridges_fill_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z "salmon">

<!-- #ffffff -->
<!ENTITY minor-roads-casing_highway_is_living_street "#ffffff">
<!ENTITY minor-roads-fill_highway_is_service_and_not_service_is_INTminus_minor "#ffffff">
<!ENTITY minor-roads-fill_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z_and_not_tunnel_is_yes "#ffffff">
<!ENTITY minor-roads-fill_highway_is_track "#ffffff">
<!ENTITY footbikecycle-tunnels_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z "#ffffff">
<!ENTITY footbikecycle-tunnels_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z "#ffffff">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade1 "#ffffff">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade2 "#ffffff">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade3 "#ffffff">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade4 "#ffffff">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#ffffff">
<!ENTITY tracks-notunnel-nobridge_tracktype_is_grade5 "#ffffff">
<!ENTITY tracks-tunnels_tracktype_is_grade1 "#ffffff">
<!ENTITY tracks-tunnels_tracktype_is_grade2 "#ffffff">
<!ENTITY tracks-tunnels_tracktype_is_grade3 "#ffffff">
<!ENTITY tracks-tunnels_tracktype_is_grade4 "#ffffff">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#ffffff">
<!ENTITY tracks-tunnels_tracktype_is_grade5 "#ffffff">
<!ENTITY bridges_casing2_railway_is_subway "#ffffff">
<!ENTITY bridges_casing2_railway_is_light_rail_or_railway_is_narrow_gauge "#ffffff">
<!ENTITY bridges_casing2_highway_is_unsurfaced "#ffffff">
<!ENTITY bridges_casing2_highway_is_bridleway_or_a_highway_is_path_and_horse_is_designated_z "#ffffff">
<!ENTITY bridges_casing2_highway_is_footway_or_a_highway_is_path_and_foot_is_designated_z "#ffffff">
<!ENTITY bridges_casing2_highway_is_path_and_not_a_bicycle_is_designated_or_foot_is_designated_or_horse_is_designated_z "#ffffff">
<!ENTITY bridges_casing2_highway_is_cycleway_or_a_highway_is_path_and_bicycle_is_designated_z "#ffffff">
<!ENTITY bridges_casing2_highway_is_byway "#ffffff">
<!ENTITY bridges_casing2_railway_is_rail "#ffffff">
<!ENTITY bridges_casing2_railway_is_INTminus_spurminus_sidingminus_yard "#ffffff">
<!ENTITY bridges_casing2_a_railway_is_disused_or_railway_is_abandoned_or_railway_is_construction_z_and_not_highway_isnot_empty "#ffffff">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade1 "#ffffff">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade2 "#ffffff">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade3 "#ffffff">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade4 "#ffffff">
<!ENTITY bridges_casing2_highway_is_track_and_tracktype_is_grade5 "#ffffff">
<!ENTITY bridges_casing2_highway_is_track_and_not_tracktype_isnot_empty "#ffffff">
<!ENTITY bridges_fill_highway_is_residential_or_highway_is_unclassified "#ffffff">
<!ENTITY bridges_fill_highway_is_service "#ffffff">
<!ENTITY bridges_fill_railway_is_rail "#ffffff">
<!ENTITY bridges_fill_railway_is_rail "#ffffff">
<!ENTITY bridges_fill_railway_is_INTminus_spurminus_sidingminus_yard "#ffffff">
<!ENTITY roads_railway_is_preserved "#ffffff">
<!ENTITY roads_railway_is_INTminus_preservedminus_ssy "#ffffff">
<!ENTITY trams_railway_is_tram_and_bridge_is_yes "#ffffff">
